# .github/FUNDING.yml

# Meu usuário no GitHub — aparecerá se e quando estiver aprovado no GitHub Sponsors
github: ['Laylow-alt']

# Meu usuário no Patreon
patreon: Laylow_alt

# Links customizados adicionais (opcionais). Você pode incluir o link ao seu post de agradecimento ou página de doação.
custom:
  - "https://www.patreon.com/cw/Laylow_alt"
  - "https://www.patreon.com/posts/obrigado-por-e-144421080"
